### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by baziz** [clintonwoo/hackernews-react-graphql#20]
When I run `npm run build && npm start`

I get 

```
> hackernews@0.5.0 build /home/basier/hackernews-react-graphql/hackernews-react-graphql
> npm run build-clean && yarn install --dev && babel src -d build/app --ignore '**/*__tests__','**/*__mocks__' && cp -R src/static build/app/static && next build build/app


> hackernews@0.5.0 build-clean /home/basier/hackernews-react-graphql/hackernews-react-graphql
> rm -rf build/app

sh: 1: yarn: not found

npm ERR! Linux 4.4.0-127-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! hackernews@0.5.0 build: `npm run build-clean && yarn install --dev && babel src -d build/app --ignore '**/*__tests__','**/*__mocks__' && cp -R src/static build/app/static && next build build/app`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the hackernews@0.5.0 build script 'npm run build-clean && yarn install --dev && babel src -d build/app --ignore '**/*__tests__','**/*__mocks__' && cp -R src/static build/app/static && next build build/app'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hackernews package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build-clean && yarn install --dev && babel src -d build/app --ignore '**/*__tests__','**/*__mocks__' && cp -R src/static build/app/static && next build build/app
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hackernews
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hackernews
npm ERR! There is likely additional logging output above.
```

**Comment by baziz** [comment]
When I run `npm run build && npm start`

I get 

```
> hackernews@0.5.0 build /home/me/hackernews-react-graphql/hackernews-react-graphql
> npm run build-clean && yarn install --dev && babel src -d build/app --ignore '**/*__tests__','**/*__mocks__' && cp -R src/static build/app/static && next build build/app


> hackernews@0.5.0 build-clean /home/me/hackernews-react-graphql/hackernews-react-graphql
> rm -rf build/app

sh: 1: yarn: not found

npm ERR! Linux 4.4.0-127-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! hackernews@0.5.0 build: `npm run build-clean && yarn install --dev && babel src -d build/app --ignore '**/*__tests__','**/*__mocks__' && cp -R src/static build/app/static && next build build/app`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the hackernews@0.5.0 build script 'npm run build-clean && yarn install --dev && babel src -d build/app --ignore '**/*__tests__','**/*__mocks__' && cp -R src/static build/app/static && next build build/app'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hackernews package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build-clean && yarn install --dev && babel src -d build/app --ignore '**/*__tests__','**/*__mocks__' && cp -R src/static build/app/static && next build build/app
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hackernews
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hackernews
npm ERR! There is likely additional logging output above.
```

With npm-debug.log yielding

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'dev' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle hackernews@0.5.0~predev: hackernews@0.5.0
6 silly lifecycle hackernews@0.5.0~predev: no script for predev, continuing
7 info lifecycle hackernews@0.5.0~dev: hackernews@0.5.0
8 verbose lifecycle hackernews@0.5.0~dev: unsafe-perm in lifecycle true
9 verbose lifecycle hackernews@0.5.0~dev: PATH: /usr/share/npm/bin/node-gyp-bin:/home/me/hackernews-react-graphql/hackernews-react-graphql/node_modules/.bin:/home/me/bin:/home/me/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/snap/bin
10 verbose lifecycle hackernews@0.5.0~dev: CWD: /home/me/hackernews-react-graphql/hackernews-react-graphql
11 silly lifecycle hackernews@0.5.0~dev: Args: [ '-c', 'babel-node src/server.js' ]
12 info lifecycle hackernews@0.5.0~dev: Failed to exec dev script
13 verbose stack Error: hackernews@0.5.0 dev: `babel-node src/server.js`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
13 verbose stack     at emitTwo (events.js:87:13)
13 verbose stack     at ChildProcess.emit (events.js:172:7)
13 verbose stack     at maybeClose (internal/child_process.js:821:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid hackernews@0.5.0
15 verbose cwd /home/me/hackernews-react-graphql/hackernews-react-graphql
16 error Linux 4.4.0-127-generic
17 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dev"
18 error node v4.2.6
19 error npm  v3.5.2
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error hackernews@0.5.0 dev: `babel-node src/server.js`
24 error spawn ENOENT
25 error Failed at the hackernews@0.5.0 dev script 'babel-node src/server.js'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the hackernews package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     babel-node src/server.js
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs hackernews
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls hackernews
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]
```

**Comment by clintonwoo** [comment]
Hi baziz, I think you probably don't have Yarn package manager installed. You can read about it here and how to install https://yarnpkg.com/lang/en/
