### ISSUE TITLE
`npm install` fails in fresh clone

### ISSUE THREAD

**Issue by langhisc** [clintonwoo/hackernews-react-graphql#24]
Bash output is below.  I do have Yarn installed.

```
Seans-MacBook-Pro:Examples seanlanghi$ git clone https://github.com/clintonwoo/hackernews-react-graphql.git && cd hackernews-react-graphql && npm install
Cloning into 'hackernews-react-graphql'...
remote: Enumerating objects: 1141, done.
remote: Total 1141 (delta 0), reused 0 (delta 0), pack-reused 1141
Receiving objects: 100% (1141/1141), 5.05 MiB | 14.31 MiB/s, done.
Resolving deltas: 100% (789/789), done.
npm WARN deprecated @zeit/check-updates@1.1.1: Please use `update-check` instead.
npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated boom@4.3.1: This version is no longer maintained. Please upgrade to the latest version.

> fsevents@1.2.4 install /Users/seanlanghi/Documents/Dev/Training/React/Examples/hackernews-react-graphql/node_modules/fsevents
> node install

node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v67-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.4 and node@11.6.0 (node-v67 ABI, unknown) (falling back to source compile with node-gyp) 
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
../fsevents.cc:63:6: warning: field 'async_resource' will be initialized after
      field 'lockStarted' [-Wreorder]
   : async_resource("fsevents:FSEvents"), lockStarted(false) {
     ^
1 warning generated.
  SOLINK_MODULE(target) Release/fse.node
  COPY /Users/seanlanghi/Documents/Dev/Training/React/Examples/hackernews-react-graphql/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64/fse.node
  TOUCH Release/obj.target/action_after_build.stamp

> grpc@1.10.1 install /Users/seanlanghi/Documents/Dev/Training/React/Examples/hackernews-react-graphql/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.10.1/node-v67-darwin-x64-unknown.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.10.1 and node@11.6.0 (node-v67 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Pre-built binaries not installable for grpc@1.10.1 and node@11.6.0 (node-v67 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Hit error Connection closed while downloading tarball file 
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
rm: ./Release/.deps/Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o.d.raw: No such file or directory
make: *** [Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o] Error 1
gyp  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/avl/avl.o
 ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:188:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/Cellar/node/11.6.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/Users/seanlanghi/Documents/Dev/Training/React/Examples/hackernews-react-graphql/node_modules/grpc/src/node/extension_binary/node-v67-darwin-x64-unknown/grpc_node.node" "--module_name=grpc_node" "--module_path=/Users/seanlanghi/Documents/Dev/Training/React/Examples/hackernews-react-graphql/node_modules/grpc/src/node/extension_binary/node-v67-darwin-x64-unknown"
gyp ERR! cwd /Users/seanlanghi/Documents/Dev/Training/React/Examples/hackernews-react-graphql/node_modules/grpc
gyp ERR! node -v v11.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/11.6.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/Users/seanlanghi/Documents/Dev/Training/React/Examples/hackernews-react-graphql/node_modules/grpc/src/node/extension_binary/node-v67-darwin-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=/Users/seanlanghi/Documents/Dev/Training/React/Examples/hackernews-react-graphql/node_modules/grpc/src/node/extension_binary/node-v67-darwin-x64-unknown' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/seanlanghi/Documents/Dev/Training/React/Examples/hackernews-react-graphql/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:188:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:978:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
node-pre-gyp ERR! System Darwin 18.2.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/11.6.0/bin/node" "/Users/seanlanghi/Documents/Dev/Training/React/Examples/hackernews-react-graphql/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /Users/seanlanghi/Documents/Dev/Training/React/Examples/hackernews-react-graphql/node_modules/grpc
node-pre-gyp ERR! node -v v11.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.7.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/Cellar/node/11.6.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/Users/seanlanghi/Documents/Dev/Training/React/Examples/hackernews-react-graphql/node_modules/grpc/src/node/extension_binary/node-v67-darwin-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=/Users/seanlanghi/Documents/Dev/Training/React/Examples/hackernews-react-graphql/node_modules/grpc/src/node/extension_binary/node-v67-darwin-x64-unknown' (1)
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/backoff/backoff.oe
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
/bin/sh: ./Release/.deps/Release/obj.target/grpc/deps/grpc/src/core/lib/backoff/backoff.o.d: No such file or directory
sed: ./Release/.deps/Release/obj.target/grpc/deps/grpc/src/core/lib/backoff/backoff.o.d.raw: No such file or directory
make: *** [Release/obj.target/grpc/deps/grpc/src/core/lib/backoff/backoff.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:188:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/Cellar/node/11.6.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/Users/seanlanghi/Documents/Dev/Training/React/Examples/hackernews-react-graphql/node_modules/grpc/src/node/extension_binary/node-v67-darwin-x64-unknown/grpc_node.node" "--module_name=grpc_node" "--module_path=/Users/seanlanghi/Documents/Dev/Training/React/Examples/hackernews-react-graphql/node_modules/grpc/src/node/extension_binary/node-v67-darwin-x64-unknown"
gyp ERR! cwd /Users/seanlanghi/Documents/Dev/Training/React/Examples/hackernews-react-graphql/node_modules/grpc
gyp ERR! node -v v11.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN eslint-config-airbnb@15.1.0 requires a peer of eslint-plugin-jsx-a11y@^5.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN enzyme-adapter-react-13@1.2.0 requires a peer of react@^0.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN enzyme-adapter-react-14@1.2.0 requires a peer of react@^0.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN enzyme-adapter-react-14@1.2.0 requires a peer of react-addons-test-utils@^0.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN enzyme-adapter-react-14@1.2.0 requires a peer of react-dom@^0.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN enzyme-adapter-react-15@1.2.0 requires a peer of react@^15.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN enzyme-adapter-react-15@1.2.0 requires a peer of react-dom@^15.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN enzyme-adapter-react-15@1.2.0 requires a peer of react-test-renderer@^15.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN enzyme-adapter-react-15.4@1.2.0 requires a peer of react@15.0.0-0 - 15.4.x but none is installed. You must install peer dependencies yourself.
npm WARN enzyme-adapter-react-15.4@1.2.0 requires a peer of react-dom@15.0.0-0 - 15.4.x but none is installed. You must install peer dependencies yourself.
npm WARN enzyme-adapter-react-15.4@1.2.0 requires a peer of react-addons-test-utils@15.0.0-0 - 15.4.x but none is installed. You must install peer dependencies yourself.
npm WARN hackernews@0.5.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.10.1 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@1.10.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/seanlanghi/.npm/_logs/2019-01-14T00_10_59_096Z-debug.log
Seans-MacBook-Pro:hackernews-react-graphql seanlanghi$ which yarn
/usr/local/bin/yarn
```

**Comment by JerryLeeCS** [comment]
Having the same problem

**Comment by JerryLeeCS** [comment]
I had to lower my node version to fix this.

**Comment by vdaranyi** [comment]
Yes, run it with node 6.7

**Comment by bizob2828** [comment]
The package.json says this though ``` "node": ">=6.9.4"```. Node 6 is EOL at the end of this month, will this be updated?

**Comment by clintonwoo** [comment]
Yes, working on updating the entire project and also changing it to TypeScript right now

**Comment by clintonwoo** [comment]
Install no longer fails on up to Node 10
